//Creando y exportando los types
export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECTS = 'ADD_PROJECTS'
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const PROJECT_CURRENT = 'PROJECT_CURRENT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const TASKS_PROJECT = 'DELETE_PROJECT';
export const ADD_TASK = 'ADD_TASKS';
export const ERROR_TAREAFORM = 'ERROR_TAREAFORM'; 
export const DELETE_TASK = 'DELETE_TASK';
export const STATE_TASK = 'STATE_TASK';
export const TASK_CURRENT = 'TASK_CURRENT';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';