//Creando y exportando los types
export const FORM_PROJECT = 'FORM_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECTS = 'ADD_PROJECTS'
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const PROJECT_CURRENT = 'PROJECT_CURRENT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const TASKS_PROJECT = 'DELETE_PROJECT';
export const ADD_TASK = 'ADD_TASKS';